chat/urls.py
from django.urls import path , re_path
from  .views import index ,room , test , login  , signin

app_name = 'chat'

urlpatterns = [
    
    path('test/' , test , name='test'),
    path('login/' , login , name='login'),
    path('signin/' , signin , name='signin'),

    path('' , index , name='index'),
    #  path('<str:room_name>/', views.room, name='room'),
    re_path(r'^(?P<room_name>[^/]+)/$' , room , name='room')
    
    
    
]

exam/urls.py
from .views import create_exam , edit_exam , index , attend ,start_exam
from django.urls import path
app_name = 'exam'



urlpatterns = [
    path('' , index , name = 'index'),
    path('attend/<int:exam_pk>/' , start_exam),
    path('attend/<int:exam_pk>/<int:question_pk>' , attend, name = 'attend'),

    path('create/<int:pk>' , index , name='create_exam'),
    path('edit/<int:pk>' , edit_exam , name='exam_edit'),
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('school_home.urls' , namespace='home')  , name = 'home'),
    path('exam/' , include('exam.urls' , namespace='exam') , name = 'exam'),
    path('class/' , include('klass.urls' , namespace='class') , name = 'class'),
    path('profile/' , include('my_profile.urls', namespace='profile') , name = 'profile'),
    path('teacher/' , include('teacher_profile.urls')),
    
]

if  settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher_profile/urls.py
from django.urls import path
from . import views
from exam.views import addq , addwq
urlpatterns = [
    path('' , views.teacher_home , name='teacher_home' ),
     path('files/delete/<int:darspk>/<int:filepk>' , views.delete_file),
    path('files/<int:pk>' , views.files , name='files'),
    path('files/create_new/<int:pk>' , views.files_create_new , name='creat-new-file'),
    path('excercise/<int:pk>' , views.excercise , name='exercise'),
    path('excercise/create_new/<int:pk>' , views.excercise_create_new , name= 'excercise_create_new'),
    path('excercise/edit/<int:pk>' , views.excercise_edit , name='excercise_edit'),
    path('tamrin_answers/<int:pk>' , views.tamrin_answers , ),
    path('exam/<int:pk>' , views.exam , name='exam'),
    path('exam/create_new/<int:pk>' , views.create_exam ),
    path('exam/addq/<int:pk>' , addq ),
    path('exam/addwq/<int:pk>' , addwq ),
   
    
]

exam/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from klass.models import Student , Teacher , Dars
from school_home.views import file_size
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validate_ans(value):
    status = value>0 and value<5

    if not status:
        raise ValidationError(
             _('%(value)s is not correct'),
             params = {'value' : value}
        )
        



class Exam(models.Model):
    
    name = models.CharField(max_length = 500)
    time_starts = models.DateTimeField()
    time_ends = models.DateTimeField()
    dars = models.ForeignKey(Dars , on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f'Exam = {self.name} , {self.dars} '

    def is_expired(self):
        return timezone.now() > self.time_ends
    
    def can_attend(self):
        return (timezone.now() > self.time_starts ) and ( timezone.now() < self.time_ends )

    
    class Meta: 
        verbose_name_plural = 'امتحانات'
        ordering = ('-time_starts' , )
    

   

class Question(models.Model):
    

    question = models.CharField(max_length=500  , blank= False , null = False)
    image = models.ImageField(upload_to = 'questions/test' , null =True , blank = True)
    # caution_help = models.CharField(max_length=500  , blank= False , null = False)
    exam = models.ForeignKey(Exam , on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    choice_one = models.CharField(max_length=150 , null=True , blank = True)
    choice_two = models.CharField(max_length=150 , null= True , blank = True)
    choice_three = models.CharField(max_length=150 , null = True , blank = True)
    choice_four = models.CharField(max_length=150 , null = True , blank = True)
    correct_ans = models.IntegerField(validators=[validate_ans , ])

    def __str__(self):
        return self.question 
    
    def summery(self):
        return '...' + self.question[:20] 

    class Meta:
        ordering = ('-date' , )
        verbose_name_plural = ' سوالات تستی'
    


class WQuestion(models.Model):

    question = models.CharField(max_length=500  , blank= False , null = False)

    image = models.ImageField(upload_to = 'questions/tashrihi' , null =True , blank = True)

    exam = models.ForeignKey(Exam , on_delete=models.CASCADE)

    date = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ('-date' , )
        verbose_name_plural = 'سوالات تشریحی'


    def __str__(self):
        return self.question
    
    def summery(self):
        return '...' + self.question[:20] 
    
    

    
class Answer_WQuestion(models.Model):
    
    answer = models.CharField(max_length=500  , null=True , blank = True)
    
    question = models.ForeignKey(Question , on_delete=models.CASCADE , null =False , )
    
    image = models.ImageField(upload_to='answers' , validators=[file_size , ])
    
    student = models.ForeignKey(Student , on_delete=models.CASCADE)

    date = models.DateTimeField(auto_now_add = True)
    
    
    class Meta:
        verbose_name_plural = 'پاسخ سوالات تشریحی'

    
    def __str__(self):
        return f'answer , {self.answer} , {self.question}'
    


class Answer(models.Model):

    question = models.ForeignKey(Question , on_delete=models.CASCADE , null =False , )
    student = models.ForeignKey(Student , on_delete=models.CASCADE)
    selected_choice = models.IntegerField(validators = [validate_ans , ] )
    date = models.DateTimeField(auto_now_add = True)



    class Meta:
        verbose_name_plural = 'پاسخ سوال های تستی'


    
    def __str__(self):
        return type(self).__name__


    


    
    

class TestModel(models.Model):
    name = models.CharField(max_length = 200)
    date_time = models.DateTimeField()
    date = models.DateField()

    def __str__(self):
        return self.name

    
 

klass/models.py
from django.db import models
from django.contrib.auth.models import  User 
import os
# Create your models here.

class Teacher(models.Model):
    
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    image = models.ImageField(upload_to='teachers')

    


    def __str__(self):
        return self.user.first_name

    
    def delete(self,*args,**kwargs):
        if os.path.isfile(self.image.path):
            os.remove(self.image.path)

        super(Teacher, self).delete(*args,**kwargs)
    class Meta:
        verbose_name_plural = "معلمان"
    
    

class Student(models.Model):

    user = models.OneToOneField(User , on_delete=models.CASCADE)
    image = models.ImageField(upload_to='students')

    class Meta:
        verbose_name_plural = "دانش آموزان"

    
    
    

    def __str__(self):
        return self.user.first_name
    


class Dars(models.Model):
    
    name  = models.CharField(max_length = 200)
    passwd = models.CharField(max_length = 20 , unique=True , blank=False , null = False)
    # image = models.ImageField(upload_to='Classes')
    Time_created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(Student)
    teacher = models.ForeignKey(Teacher , on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "دروس"

    def __str__(self):
        return self.name
from django.utils import timezone

class Tamrin(models.Model):

    name = models.CharField(max_length = 300)

    dars = models.ForeignKey(Dars , on_delete=models.CASCADE)

    file = models.FileField(upload_to=f'tamrin/{dars.name}')

    time_created = models.DateTimeField(auto_now_add=True)

    time_expire = models.DateTimeField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('time_expire',)
        verbose_name_plural = 'تمارین   '

    def is_expired(self):
        return timezone.now() > self.time_expire
    
    def is_solved(self):
        pass
    

                                                 
class File_teacher(models.Model):
    name = models.CharField(max_length=300)
    dars = models.ForeignKey(Dars , on_delete=models.CASCADE)
    file = models.FileField(upload_to='klass/Files_teacher')
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-time' , )

    def __str__(self):
        return self.name

teacher_profile/models.py
from django.db import models

# Create your models here.

exam/forms.py
from django import forms
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from .models import TestModel , Answer , Exam , Question , WQuestion
from django.utils.translation import gettext as _

class TestForm(forms.ModelForm):
    class Meta:
        model = TestModel
        fields = ('name', 'date_time' , 'date')

    def __init__(self, *args, **kwargs):
        super(TestForm, self).__init__(*args, **kwargs)
        self.fields['date'] = JalaliDateField(label=_('date'), # date format is  "yyyy-mm-dd"
            widget=AdminJalaliDateWidget # optional, to use default datepicker
        )

        # you can added a "class" to this field for use your datepicker!
        # self.fields['date'].widget.attrs.update({'class': 'jalali_date-date'})

        self.fields['date_time'] = SplitJalaliDateTimeField(label=_('date time'), 
            widget=AdminSplitJalaliDateTime # required, for decompress DatetimeField to JalaliDateField and JalaliTimeField
        )
        



class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ( 'time_starts' , 'time_ends' , 'name')


    def __init__(self, *args, **kwargs):
        super(ExamForm, self).__init__(*args, **kwargs)
        

        # you can added a "class" to this field for use your datepicker!
        # self.fields['date'].widget.attrs.update({'class': 'jalali_date-date'})

        self.fields['time_starts'] = SplitJalaliDateTimeField(label=_('date time'), 
            widget=AdminSplitJalaliDateTime # required, for decompress DatetimeField to JalaliDateField and JalaliTimeField
        )
        self.fields['time_ends'] = SplitJalaliDateTimeField(label=_('date time'), 
            widget=AdminSplitJalaliDateTime # required, for decompress DatetimeField to JalaliDateField and JalaliTimeField
        )

teacher_profile/forms.py
from django import forms
from klass.models import Tamrin  , File_teacher
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from django.utils.translation import gettext as _

class Create_Tamrin_Form(forms.ModelForm):
    class Meta:
        model = Tamrin
        fields = ('name' , 'time_expire' , 'file' ,)

    def __init__(self, *args, **kwargs):
        super(Create_Tamrin_Form, self).__init__(*args, **kwargs)
        # self.fields['time_created'] = JalaliDateField(label=_('date time'), # date format is  "yyyy-mm-dd"
        #     widget=AdminJalaliDateWidget # optional, to use default datepicker
        # )

        # you can added a "class" to this field for use your datepicker!
        # self.fields['date'].widget.attrs.update({'class': 'jalali_date-date'})

        self.fields['time_expire'] = SplitJalaliDateTimeField(label=_('date time'), 
            widget=AdminSplitJalaliDateTime # required, for decompress DatetimeField to JalaliDateField and JalaliTimeField
        )

class File_teacher_form(forms.ModelForm):
    class Meta:
        model = File_teacher
        fields = ['name' , 'file' ,]

exam/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.utils.safestring import mark_safe
import json
from .forms import TestForm , ExamForm 
from klass.models import Teacher , Student  , Dars
from .models import Exam
from django.utils import timezone
from .models import Question , WQuestion
from django.views.decorators.csrf import csrf_protect , csrf_exempt
from django.http import JsonResponse

def index(request , template_name = 'exam/index.html' , pk = None):
    form = ExamForm(request.POST or None)
    user = request.user
    teacher = get_object_or_404(Teacher , user = user)
    dars = get_object_or_404(Dars , id = pk , teacher = teacher)

    if request.method == 'POST':
        if form.is_valid():

            name = form.cleaned_data['name']
            time_starts = form.cleaned_data['time_starts']
            time_ends = form.cleaned_data['time_ends']
            exam = Exam.objects.create(name = name , dars = dars , time_starts = time_starts , time_ends = time_ends)
            from django.http import HttpResponse
            return redirect(f'/teacher/exam/create_new/{exam.id}')
        else :
            return HttpResponse('Exam not  Created')
    

    return render(request , template_name , {   'form':form  , })


@csrf_exempt
def attend(request , template_name = 'exam/attend.html' , exam_pk = None  , question_pk = None):

    this_exam = get_object_or_404(Exam , id = exam_pk)

    if  not this_exam.can_attend:
        return HttpResponse('time out ')

    questions = Question.objects.filter(exam = this_exam) 

    wquestions = WQuestion.objects.filter(exam = this_exam)

    questions_count = questions.count()

    this = Question.objects.get(id = question_pk)

    user = request.user

    student = get_object_or_404(Student , user = user)

    print(this)

    time = timezone.now()

    if request.method == 'POST':
        
        file = request.FILES['file']
        user = request.user

    data = {

        'exam' : this_exam ,
        'questions' : questions , 
        'wquestions' : wquestions,
        'this' : this  ,
        'time': time,
        'num' : questions_count,
        'student' : student ,

  
            }

    return render(request , template_name , data)


@csrf_exempt
def addq(request , template_name='exam/addq.html' , pk=None):

    user = request.user
    teacher = get_object_or_404(Teacher , user = user)
    exam = get_object_or_404(Exam , id = pk)

    if request.method == "POST":
        file = request.FILES['file']
        post_data = request.POST
        question = post_data['question']
        choice_one = post_data['choice_one']
        choice_two = post_data['choice_two']
        choice_three = post_data['choice_three']
        choice_four =  post_data['choice_four']
        correct_ans = post_data['correct_ans']
       
        Question.objects.create(exam  = exam , image = file , question = question , choice_four = choice_four , choice_one = choice_one , choice_two = choice_two , choice_three = choice_three , correct_ans = correct_ans)
        return JsonResponse({'message' : 'ok' } , status = 200)     
    

    data ={
     
        'exam' : exam,
    }

    return render(request , template_name , data)



@csrf_exempt
def addwq(request , template_name='exam/addwq.html' , pk=None):
    user = request.user
    teacher = get_object_or_404(Teacher , user = user)
    exam = get_object_or_404(Exam , id = pk)

    if request.method == "POST":
        file = request.FILES['file']
        post_data = request.POST
        question = post_data['question']
        WQuestion.objects.create(exam = exam , image = file  , question = question )
        return JsonResponse({'message' : 'ok' } , status = 200)

    data ={
    'exam' : exam ,
    }

    return render(request , template_name , data)









def start_exam(request , exam_pk = None):

    exam = get_object_or_404(Exam , id = exam_pk)

    if Question.objects.filter(exam  = exam ).exists():
         first = Question.objects.filter(exam=exam).first()
    else :
        first = WQuestion.objects.filter(exam =exam).first()

    return redirect(f'/exam/attend/{exam_pk}/{first.id}')
    


























def create_exam(request, template_name = 'exam/create_exam.html' ):
    
    
    return render(request , template_name)


def edit_exam(request ,template_name = 'exam/edit_exam.html' , pk = None ):
     
     data = {}
     data['pk'] = pk
     return render(request , template_name ,  data)

teacher_profile/templates/teacher_profile/base.html
{% load static %}



<html dir="rtl">


	<head>
		<meta charset="UTF-8" />
		<title>   پنل {{user.first_name}} </title>
		

				<meta name="apple-mobile-web-app-capable" content="yes">

		{% include 'my_profile/links.html' %}

	</head>




		<body class="skin-black">
		<div id="ajaxloader" style="text-align: center; position: fixed; z-index: 6000; width: 100%; height: 100%; display: none;  background-color: black; opacity: 0.5; padding-top: 25%;">
			<img alt="در حال بارگذاری..." src=" {% static "my_profile/templates/userindex/img/loading-bars.svg" %}" style="width: 100px;"/>
		</div>
		<div id="tooltip"></div>
		<div id="alertBox">
			<div id="messagealerter" class="alert_wrapper"></div>
		</div>
		{% include 'teacher_profile/header.html' %}
		

		<div class="wrapper row-offcanvas row-offcanvas-left" style="margin-top: 50px;" >

		 {% include 'teacher_profile/aside.html' %}


        <div class="container">
		  {% block content %}
		   
		  {% endblock content %}
		</div>




				
									<script>
						$('a[href *= "app=azmon"]').parent().parent().parent().addClass('active');
						$('a[href *= "app=azmon"]').parent().addClass('active');
					</script>
								<aside id="right-side" class="right-side">
				<div id="ajaxcontent" style="margin: 0px; padding: 0px; min-height: 450px;">

				<section class="content-header">
					<h1 style="padding: 0px 20px 5px 20px;" ><small>

					</small></h1>
				</section>

				<section class="content" style="padding-bottom: 280px;">
	<div id="masir" >
			</div>
	<div id="box" >
		<div id="box2" >
			<div id="container">
				<table class="table table-striped table-bordered table-hover"></table>			</div>
		</div>
	</div>

				</section>
				</div>
				<br/>
			</aside>
		</div>
		<script src=" {% static "my_profile/templates/userindex/js/bootstrap.min.js" %}" type="text/javascript"></script>
		<script src=" {% static "my_profile/templates/userindex/js/app.js" %} " type="text/javascript"></script>
				<script>
							jQuery('#ajaxloader').fadeOut(400);
							jQuery('#ajaxloader').click(function () {
								jQuery(this).fadeOut(400);
							});
							$('.dropdown-toggle').click(function () {
								jQuery(this).next('.dropdown-menu').slideToggle();
								return false;
							});
		</script>
		<style>
			.copyright {
				position: fixed;
				bottom: -10px;
				left: 0px;
				width: 100%;
				padding: 5px;
				text-align: center;
				color: rgb(111, 111, 111);
				background-color: rgb(222, 222, 222);
			}
			.copyright a{
				color: rgb(11, 11, 11);
			}
			.copyright a:hover{
				text-shadow: 0px 0px 1px #fff;
				text-decoration: none;
			}
		</style>
						<p class="copyright" dir="rtl">
					
					<a target="_blank" href="http://www.sadatmand.ir/" style='font-family:"byekan"'>
					 گروه مهندس سعادتمند 
					</a>
				</p>
			
					</body>
					
</html>

teacher_profile/templates/teacher_profile/exam.html
{% extends 'teacher_profile/base.html' %}
{% load jalali_tags %}

 


{% block content %}
 
 <style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
      }
      .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
      }
      .container {
        padding: 2px 16px;
      }
</style>
 

<center>

 <h3 style="font-family: 'byekan'; color:green;"> امتحانات {{dars.name}} </h3>

 <a href = '/exam/create/{{dars.id}}'>
 <button type="button" class="btn btn-success" style='font-family:"byekan"' >برای ایجاد امتحان جدید کلیک کنید</button></a>

   {% for exam in exams  %}
   {% if  exam.is_expired %}


     <div class="card" text-align='center' align-items= 'center'>

    <div class="container" style='align-items:right'>
      <h4><b style='font-family:"byekan"'>{{exam.name  }}</b></h4>
  
      <a href='/teacher/exam/files/{{exam.id}}'>
      <button type="button" class="btn btn-info" style='font-family:"byekan"' >دانلود پاسخ نامه های دنش آموزان</button></a>
      </div>
      </div>
      
       
      
      
        
{% elif exam.can_attend %}
 <div class="card" text-align='center' align-items= 'center'>

    <div class="container" style='align-items:right'>
      <h4><b style='font-family:"byekan"'>{{exam.name  }}</b></h4>
  
      <a href='#'>
      <button type="button" class="btn btn-Info" style='font-family:"byekan"' > امتحان در حال برگزاری است</button></a>
      </div>
      </div>


   {% else %}

     <div class="card">

    <div class="container" style='align-items:right'>
      <h4><b style='font-family:"byekan"'>{{exam.name  }}</b></h4>
  
      <a href='#'>
      <button type="button" class="btn btn-primary" >زمان شروع امتحان <div > روز {{exam.time_starts|to_jalali:'%m/%d  '}}</div><span>ساعت{{exam.time_starts|to_jalali:'%H/%M'}} </span></button></a>

       <br > 
       <br > 
      <a href='/teacher/exam/create_new/{{exam.id}}'>
      <button type="button" class="btn btn-Info" style='font-family:"byekan"' > ویرایش سوالات</button></a>

      </div>
      </div>
   {% endif %}
   {% endfor %}

</center>
	
{% endblock content %}

teacher_profile/templates/teacher_profile/excercise.html
{% extends 'teacher_profile/base.html' %}
{% load jalali_tags %}

 


{% block content %}
 
 <style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
      }
      .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
      }
      .container {
        padding: 2px 16px;
      }
</style>
 

<center>
 <h3 style="font-family: 'byekan'; color:green;">  تمارین {{dars.name}} </h3>
 </center>
 <a href = '/teacher/excercise/create_new/{{dars.id}}'>
 <button type="button" class="btn btn-primary" style='font-family:"byekan"' >برای ایجاد تمرین جدید کلیک کنید</button></a>

{% comment %} <form method="post">
{% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary mb-2">Confirm identity</button>
</form>  {% endcomment %}

   {% for tamrin in tamrins  %}
  
<center>

   <div class="card">

    <div class="container" style='align-items:right'>
      <h4><b style='font-family:"byekan"'>{{tamrin.name  }}</b></h4>
  
      <a href={{tamrin.file.url}}>
      <button type="button" class="btn btn-primary" style='font-family:"byekan"' >دانلود</button></a>
      
     
      
       <p style='font-family:"byekan"'>حداکثر مهلت تحویل تمرین</p>
      <p>{{tamrin.time_expire|to_jalali:'%m/%d  %H:%M'}}</p>


      {% comment %} <a href='/teacher/excercise/edit/{{tamrin.id}}'>
      <button type="button" class="btn btn-success" style='font-family:"byekan"' >ویرایش تمرین</button></a> {% endcomment %}



      
      {% comment %} <form method='post'  enctype="multipart/form-data">

         {{form.file}}
         <input type="hidden" id="custId" name="tamrin" value="{{tamrin.id}}">
         
         <input type="submit" value="فرستادن">

    <script type="text/javascript">
        $('#id_file').bind('change', function() {
          if (this.files[0].size/1000000 > 200){
            alert('حجم فایل انتخابی بسیار زباد است');
            this.files[0] = null;
          }        
        });
    </script>
      </form> {% endcomment %}
       <p>
      {% comment %} {% if tamrin.is_expired %} {% endcomment %}
       <a href = "/teacher/tamrin_answers/{{tamrin.id}}">
         <button type="button" class="btn btn-info" style='font-family:"byekan"' > دریافت پاسخ های فرستاده شده</button> </a>
      {% comment %} {% endif %} {% endcomment %}
        
      </p>
    </div>
  </div>
</center> 


{% endfor %} 
	
{% endblock content %}

teacher_profile/templates/teacher_profile/excercise_create_new.html
{% load static %}

<head>
     <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 
    <link rel="stylesheet" type="text/css" href=" {% static "pfont.css"  %}">
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
		<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
</head>
{% load jalali_tags %}
<center style="font-family: 'byekan';">
{{dars}}


<form method="POST" enctype="multipart/form-data">
{% csrf_token %}


{{form.name}} 
<label for="id_name">نام  تمرین</label>

<br />

<label for="id_time_expire_0">تاریخ دقیق تحویل</label>
{{form.time_expire}}
<br>
<label for="id_file">فایل مورد نظر را انتخاب کنید</label>
<br>
{{form.file}}
<br>

<button type="submit" class="btn btn-primary mb-2" style="font-family: 'byekan';">تایید و فرستادن</button>

</form>
</center>   

teacher_profile/templates/teacher_profile/excercise_edit.html
<p> this edit Excercise with pk = {{pk}} </p>

teacher_profile/templates/teacher_profile/files.html
{% extends 'teacher_profile/base.html' %}
{% load jalali_tags %}
 <style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
      }
      .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
      }
      .container {
        padding: 2px 16px;
      }
</style>
 
{% block content %}

<center>
 <h3 style="font-family: 'byekan'; color:green;"> فایل های {{dars.name}} </h3>

 <a href = '/teacher/files/create_new/{{dars.id}}'>
 <button type="button" class="btn btn-primary" style='font-family:"byekan"' >برای قراردادن فایل جدید کلیک کنید</button></a>
</center>

{% for file in files %}
<hr />
<center>

   <div class="card">

    <div class="container" style='align-items:right'>
      <h4><b style='font-family:"byekan"'>{{file.name  }}</b></h4>
  
      <a href={{file.file.url}}>
      <button type="button" class="btn btn-primary" style='font-family:"byekan"' >دانلود</button></a>
      
     
      
      <a href='/teacher/files/delete/{{dars.id}}/{{file.id}}'>
      <button type="button" class="btn btn-danger" style='font-family:"byekan"' >حذف </button></a>
     
    </div>
  </div>
</center> 
</center>

{% endfor %}
{% endblock content %}

teacher_profile/templates/teacher_profile/tamrin_answers.html
{% extends "teacher_profile/base.html" %}
 
 <style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
      }
      .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
      }
      .container {
        padding: 2px 16px;
      }
</style>

{% block content %}
<center>
 <h3 style="font-family: 'byekan'; color:green;">  پاسخ تمارین {{tamrin.name}} </h3>
 </center>

{% for answer in answers %}

<div class="card">
   <center>
    <div class="container" style='align-items:right'>
        <h4><b style='font-family:"byekan"'> پاسخ {{answer.student  }}</b></h4>
    
        <a href={{answer.file.url}}>
        <button type="button" class="btn btn-info" style='font-family:"byekan"' >دانلود</button></a>

        </center>
        

</div>
 
  
{% endfor %}

{% endblock content %}